### ISSUE TITLE
Python: Cannot create new attributes on node

### ISSUE THREAD

**Issue by Rulasmur** [gephi/gephi-plugins#172]
When I attempt:
`
nde = g.addNode(label="Test",color=blue, size=5.0)
nde.gender = "female"
`
I get the error:
`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IllegalArgumentException: java.lang.IllegalArgumentException: The column 'gender' is not found
`

has the feature been removed or am I misunderstanding something?

**Comment by eduramiba** [comment]
Mmm it's possible that you now need to add the column first, I will check it.

**Comment by xander2508** [comment]
Hey was this ever solved?

**Comment by brad-alexander** [comment]
found that you can add a column like so:
```python
>>> n = iter(g.nodes).next() # get any node
>>> n.newcolumn = "yay"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IllegalArgumentException: java.lang.IllegalArgumentException: The column 'newcolumn' is not found
>>> import java
>>> n.node.table.addColumn("newcolumn", java.lang.String)
newcolumn (class java.lang.String)
>>> n.newcolumn = "yay"
>>>
```
