### ISSUE TITLE
leiden-modularity-plugin: Crashes when filters are active?

### ISSUE THREAD

**Issue by deklanw** [gephi/gephi-plugins#216]
@vtraag

Environment: Windows. v0.9.2.

The plugin works fine when I haven't applied any filters. If I apply a filter and run it it stops immediately, there is no popup window, and I see `Leiden algorithm    0` in the panel on the right. If I try to run it again I see a spinner and the program becomes unresponsive. I have to close with Task Manager

**Comment by vtraag** [comment]
Thanks for reporting the issue! I will look into it.

**Comment by vtraag** [comment]
This is normal behaviour. For a certain resolution parameter lower than some threshold, you will always find a single cluster.

This is probably not the most relevant clustering, so you might want to use one of the higher resolution parameters. What resolution parameter(s) is/are best suited for your particular analysis depends on the context and your needs. Feel free to simply mail me, then we don't clutter this issue.

**Comment by mbastian** [comment]
Hi @vtraag I can also reproduce this issue. I've assigned it to you but I'm happy to assist if needed.

This is the exception I received
```
java.lang.IllegalArgumentException: Last element of firstNeighborIndices array must be equal to nEdges.
	at cwts.networkanalysis.Network.checkIntegrity(Network.java:1199)
	at cwts.networkanalysis.Network.<init>(Network.java:1374)
	at cwts.networkanalysis.Network.<init>(Network.java:275)
	at cwts.networkanalysis.gephiplugin.RunClustering.execute(RunClustering.java:111)
	at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:163)
	at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:150)
```
