### ISSUE TITLE
500 error on Publish

### ISSUE THREAD

**Issue by 73616e646572** [gephi/gephi-plugins#289]
Same here, confirmation and connection works. Clicking `Publish your network to the web!` results in a progress bar with `Publishing to Gist` in the bottom right and indeed the error `Error creating online gexf file. Error code:500; Error message:`.  The extended error log looks as follows:

```
net.clementlevallois.web.publish.plugin.exceptions.PublishToGistException: Error creating online gexf file. Error code:500; Error message:
	at net.clementlevallois.web.publish.plugin.github.PublishRunnable.postGexfToGist(PublishRunnable.java:204)
	at net.clementlevallois.web.publish.plugin.github.PublishRunnable.run(PublishRunnable.java:63)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.call(LongTaskExecutor.java:336)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

_Originally posted by @73616e646572 in https://github.com/gephi/gephi-lite/issues/23#issuecomment-1383774420_

**Comment by seinecle** [comment]
Don't hesitate upvoting my post on the link above.
