### ISSUE TITLE
scripting-plugin migration help

### ISSUE THREAD

**Issue by pardypaddy** [gephi/gephi-plugins#79]
Hi Everyone,
since I was working with the scripting plugin for Gephi 0.8 for a long time, and didn't want to wait for someone else to do the update to 0.9, I did most of the code and dependency changes that were necessary- including migration to maven. Unfortunately, I need help with the dependency management! For simplicity, I did not implement Filters yet. The build runs fine, but when I install it in Gephi and want to open the Console, it crashes with java.lang.IllegalStateException: Cannot find TopComponent with preferredID ConsoleTopComponent, see IDE log for more details.
I attached the projects as .zip.
[scripting_api_working.zip](https://github.com/gephi/gephi-plugins/files/115443/scripting_api_working.zip)
[desktop-scripting.zip](https://github.com/gephi/gephi-plugins/files/115452/desktop-scripting.zip)
[gython_wrapper.zip](https://github.com/gephi/gephi-plugins/files/115450/gython_wrapper.zip)
[scripting_plugin.zip](https://github.com/gephi/gephi-plugins/files/115451/scripting_plugin.zip)

You can find the ConsoleTopComponent.java file in the desktop-scripting scr. I would appreciate any help or feedback!

**Comment by pardypaddy** [comment]
@luizribeiro @mbastian maybe you guys can have a look.. would be great, if we can get it back working on 0.9...

**Comment by pardypaddy** [comment]
Hi, I'm a bit unhappy, since noone has approved on this issue yet :(
I did a new approach and merged all Plugins into one. The dependency management and build works fine as before, but there is the same error after installation and selecting "new project":
`java.lang.NullPointerException
	at org.gephi.desktop.scripting.ConsoleTopComponent.newJythonConsole(ConsoleTopComponent.java:156)
	at org.gephi.desktop.scripting.ConsoleTopComponent.updateCurrentConsole(ConsoleTopComponent.java:135)
	at org.gephi.desktop.scripting.ConsoleTopComponent.access$000(ConsoleTopComponent.java:82)
	at org.gephi.desktop.scripting.ConsoleTopComponent$1.select(ConsoleTopComponent.java:101)
	at org.gephi.project.impl.ProjectControllerImpl.fireWorkspaceEvent(ProjectControllerImpl.java:330)
	at org.gephi.project.impl.ProjectControllerImpl.openWorkspace(ProjectControllerImpl.java:274)
	at org.gephi.project.impl.ProjectControllerImpl.openProject(ProjectControllerImpl.java:233)
	at org.gephi.project.impl.ProjectControllerImpl.newProject(ProjectControllerImpl.java:118)
	at org.gephi.desktop.project.ProjectControllerUIImpl.newProject(ProjectControllerUIImpl.java:498)
	at org.gephi.branding.desktop.actions.NewProject.actionPerformed(NewProject.java:54)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)`

I figured out, that there must be something wrong with the PythonInterpreter initialization, but I don't know where exactly the error comes from.. 
It would be great, if someone could help me out of this :)
Check out the merged version on https://www.dropbox.com/s/amgqqtqsk9fi2v2/ScriptingPlugin2.zip?dl=0

**Comment by eduramiba** [comment]
Hi Patrick,
Thank you for working on this, I will take a look as soon as possible.

Cheers,
Eduardo

**Comment by pardypaddy** [comment]
Hi Eduardo, 
I guess the dropbox link for the merged version is not working anymore so here it is again:
https://www.dropbox.com/s/amgqqtqsk9fi2v2/ScriptingPlugin2.zip?dl=0
It seems like the unmerged version causes fewer errors on runtime, but it's still failing with the error above.. 

What I did to migrate it to Gephi 0.9, was following the instructions for Plugin Migration with Maven, and then correcting all the Errors in the Code (mainly ScriptingAPI was affected), which occured with the Core API changes.

Thank you very much for your concern!
Best regards,
Patrick

**Comment by pardypaddy** [comment]
Hi @eduramiba, did you manage to have a look? It would be nice to know what's wrong..

**Comment by eduramiba** [comment]
Hi Patrick,
Sorry for the wait, I don't have much free time lately and have not checked this yet.

**Comment by pardypaddy** [comment]
No Problem at all ;) I will rework it now and let you guys know, if it improved somehow.

**Comment by eduramiba** [comment]
Hi Patrick,
I think I found the problem and will keep working on this.

Did you make any changes I should take into account?
Thank you,
Eduardo

**Comment by eduramiba** [comment]
Got it to work! I will fix a few UI problems also :)

**Comment by eduramiba** [comment]
I pushed the code here https://github.com/gephi/gephi-plugins/tree/python-scripting-plugin

**Comment by pardypaddy** [comment]
Hey Eduardo,

Thats awesome! Unfortunately I did not work on this anymore. I will have a look in the evening :)
Good job!
Cheers,
Pat

**Comment by eduramiba** [comment]
I think everything works fine now.
Only problem I see is that sometimes (perspective changed or window position changed) the keyboard focus is lost somehow and you can't write to the console. You have to switch application and switch back for it to work.

Any idea?

**Comment by eduramiba** [comment]
I think I will just merge this with that small issue since it has a workaround.

**Comment by eduramiba** [comment]
PR created #106
