### ISSUE TITLE
null pointer exception 

### ISSUE THREAD

**Issue by AmaniChou** [gephi/gephi-plugins#88]
I implemented a new metric for node. in my loop on the graph nodes, I use 
`n.setAttribute(NEWMETRIC, newMetric)` to add the computed value in the nodes table.
I already used` nodeTable.addColumn(NEWMETRIC, NbBundle.getMessage(NewMetric.class, "NewMetric.nodecolumn.NewMetric"), Double.class, 0.0);
    ` to add the column to the nodes table.
the null pointer is located in the setAtrribute instruction.
Did I miss somthing ?
PS: my class iimplements only statisctics interface 
Exception:
`java.lang.NullPointerException
	at org.gephi.graph.impl.ElementImpl.checkColumn(ElementImpl.java:705)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:318)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:313)
`

**Comment by mbastian** [comment]
Hi, can you share your code as this is not straightforward and maybe you're not initializing something correctly.
